@startuml Three Layer Design Diagram

package presentation {
    +class MainApp {
        +MainApp(args: String[])
    }

    +class GameComponent {

    }

    +class GameAdvanceListener {

    }
}

package domain {
    +class GameInstance {

    }

    +abstract class Actor {
        
    }

    +class Player {
        
    }

    +class Enemy {

    }
}

package datasource {

}

@enduml