name: Build JAR
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish'
        required: true
        type: boolean
        default: true
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: indiana-ghost
          path: build/libs/*.jar